### ISSUE TITLE
[Suggestion] Allow custom className

### ISSUE THREAD

**Issue by operfildoluiz** [guilouro/formcat#9]
_First of all, congratulations! Your work in this project was awesome_

I have a suggestion. Let's suppose I have a `<InputField>` and I want to add the "isinput" className.

By now, I'll have to:

1. Create a CustomField using HOC
2. Inject a commom HTML input file
3. Set the className
4. Import the customfield in my component

It works? Yep... But could be better:

```
<InputField
     className="isinput" <----
     name="name" />
```

And the component InputField would add the prop className in the native input element

What do you think? If makes sense, I'd be glad to help to achieve that o/

**Comment by guilouro** [comment]
Hey @operfildoluiz !! Thanks a lot for this issue

Yes, it makes sense and it should be the default behavior.

I looked for fastly and I think it could be fixed in this line:
https://github.com/guilouro/formcat/blob/master/src/fields/Wrapper.js#L7

We need to pass forward the className prop in Wrapper and use this props instead of empty string

Feel free to open a PR or if you prefer I can do this until at night.

Thanks again for your issue
